deployment:
  tasks:
    - export DEPLOYPATH=/home4/joanes03/public_html
    - echo "🚀 Iniciando deploy para $DEPLOYPATH"
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH/
    - echo "✅ Deploy concluído em $(date)" >> /home4/joanes03/deploy.log
