deployment:
  tasks:
    - export DEPLOYPATH=/home4/SEU_USUARIO/public_html
    - echo "🚀 Iniciando deploy para $DEPLOYPATH"
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH/
    - echo "✅ Deploy concluído em $(date)" >> /home4/SEU_USUARIO/deploy.log
